[package]
name = "wesl-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
wesl-parse = { path = '../wesl-parse' }
wgsl-spec = { workspace = true, features = ["include"]  }
im = { workspace = true }